name: Keep Streamlit apps awake
on:
  schedule:
    - cron:  "0 */6 * * *"
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }

      - name: Install Python deps
        run: pip install selenium~=4.21

      - name: Run wake-up script
        run: python wake_up_streamlit.py     # ← the Selenium script you saved

      - uses: actions/upload-artifact@v4
        with:
          name: wake-log
          path: wake_log.txt
