name: Keep Streamlit apps awake

on:
  schedule:
    # minute 0 every 3rd hour  → 00, 03, 06, 09, 12, 15, 18, 21 UTC
    - cron: "0 */3 * * *"
  workflow_dispatch:

concurrency:                      # never let two runs overlap
  group: keep-streamlit-awake
  cancel-in-progress: true

jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️  Checkout repo
        uses: actions/checkout@v4

      - name: 🐍  Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 📦  Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium~=4.21 fake-useragent~=1.5

      - name: 🔔  Wake Streamlit apps
        run: python wake_up_streamlit.py

      - name: 📄  Upload wake log
        uses: actions/upload-artifact@v4
        with:
          name: wake-log
          path: wake_log.txt
