name: Keep Streamlit apps awake
on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install selenium~=4.21 fake-useragent~=1.5
      - run: python wake_up_streamlit.py
